const TYPE_CONFIG = {
  strength: { icon: '✦', label: 'Strength', color: 'text-[#3fb950]', bg: 'bg-[#0d2b15]', border: 'border-[#1a4a2a]' },
  opportunity: { icon: '◎', label: 'Opportunity', color: 'text-[#ffa657]', bg: 'bg-[#2d1f0a]', border: 'border-[#4a3515]' },
  tip: { icon: '⚡', label: 'Pro Tip', color: 'text-[#79c0ff]', bg: 'bg-[#0a1f2d]', border: 'border-[#153045]' },
  error: { icon: '⚠', label: 'Error', color: 'text-[#f85149]', bg: 'bg-[#2d0a0a]', border: 'border-[#4a1515]' },
};

function InsightCard({ item }) {
  const cfg = TYPE_CONFIG[item.type] || TYPE_CONFIG.tip;
  return (
    <div className={`${cfg.bg} border ${cfg.border} rounded-xl p-5`}>
      <div className={`flex items-center gap-2 mb-3 ${cfg.color}`}>
        <span className="text-lg">{cfg.icon}</span>
        <span className="text-sm font-semibold uppercase tracking-wider">{cfg.label}</span>
      </div>
      <p className="text-[#e6edf3] text-sm leading-relaxed">{item.insight}</p>
    </div>
  );
}

export default function AIInsights({ insights, user }) {
  return (
    <div>
      <div className="flex items-center gap-3 mb-6">
        <h2 className="text-[#e6edf3] font-semibold text-lg">AI Insights</h2>
        <span className="px-2.5 py-0.5 bg-[#1f2937] border border-[#374151] rounded-full text-xs text-[#8b949e]">
          Powered by Llama 3
        </span>
      </div>

      {!insights && (
        <div className="flex flex-col items-center justify-center h-40 gap-3">
          <div className="w-6 h-6 border-2 border-[#388bfd] border-t-transparent rounded-full animate-spin" />
          <div className="text-[#8b949e] text-sm">Analyzing {user?.login}'s coding patterns…</div>
        </div>
      )}

      {insights && (
        <div className="flex flex-col gap-4 max-w-2xl">
          {insights.map((item, i) => (
            <InsightCard key={i} item={item} />
          ))}

          <div className="card p-4 mt-2">
            <div className="text-[#6e7681] text-xs leading-5">
              These insights are generated by AI based on public GitHub activity data.
              They reflect patterns in commit history, language usage, and repository activity.
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
